#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'

cookbook 'php', '~> 1.4.6'

cookbook "php55",
  :git => "https://github.com/aporat/php55-cookbook"

cookbook 'php-mcrypt', '~> 1.0.0'

cookbook 'apache2', '>= 1.0.0'

cookbook 'mysql', '~> 5.5.2'

cookbook 'composer', '~> 1.0.5'
